steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.production'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/qa-space-backend:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/qa-space-backend:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'qa-space-backend'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/qa-space-backend:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - '${_SERVICE_ACCOUNT}'
      - '--add-cloudsql-instances'
      - '${_CLOUDSQL_INSTANCE}'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'DATABASE_URL=qa-space-secrets:latest,DATABASE_URL'
      - 'JWT_ACCESS_SECRET=qa-space-secrets:latest,JWT_ACCESS_SECRET'
      - 'JWT_REFRESH_SECRET=qa-space-secrets:latest,JWT_REFRESH_SECRET'
      - 'S3_BUCKET=qa-space-secrets:latest,S3_BUCKET'
      - 'S3_REGION=qa-space-secrets:latest,S3_REGION'
      - 'S3_ENDPOINT=qa-space-secrets:latest,S3_ENDPOINT'
      - 'S3_ACCESS_KEY=qa-space-secrets:latest,S3_ACCESS_KEY'
      - 'S3_SECRET_KEY=qa-space-secrets:latest,S3_SECRET_KEY'
      - 'ALLOWED_ORIGINS=qa-space-secrets:latest,ALLOWED_ORIGINS'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'

substitutions:
  _REGION: 'us-central1'
  _SERVICE_ACCOUNT: 'qa-space-backend@${PROJECT_ID}.iam.gserviceaccount.com'
  _CLOUDSQL_INSTANCE: '${PROJECT_ID}:${_REGION}:qa-space-db'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

